language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - rubinius-2
  - jruby-9000
before_install:
  - gem update bundler
addons:
  code_climate:
    repo_token: 2c2c7c253435c02667371778ca886b069d4d24590748fbd7396b9b080016bfa7
notifications:
  email: false
